### ISSUE TITLE
Hyperledger Fabric用語リスト

### ISSUE THREAD

**Issue by NaikiU** [linuxfoundation-jp/HL_Fabric_Doc-Jp#2]
お世話になります。
現在Hyperledger Fabric管理コース(LFD272）の翻訳をしているのですが、基礎コース（LFD271）で使用している単語とTerm listの以下の単語が一部異なるため、どちらを採択するか悩んでおります。
特にordererが英語のままなのに対し、似た要素のピアとエンドーサーはカタカナになっております。committerはリストにありませんが、これもコミッターでしょうか？（committing peerはリストでコミットピアになってます。）

恐れ入りますが、以下の単語について皆様のご意見を伺いたく存じます。よろしくお願いします。

（英語、Term list、LFD271の順）
centralized　中央集権的　中央集権型
committing peer　コミットピア　コミッティングピア
committer　（登録なし）　committer
consensus　合意形成　コンセンサス
crypto material　暗号マテリアル　暗号材料
decentralized　非中央集権的　非中央集権型
endorser　エンドーサー　endorser
endorsment　エンドースメント　承認
enterprise　エンタープライズ　企業
identity　アイデンティティ　ID
interface　インタフェース　インターフェイス
peer　ピア　peer
request　要求　リクエスト
return　リターン　返す
read set　読み込みセット　read set
write set　書き込みセット　write set

**Comment by satota2** [comment]
Glossaryページ翻訳レビューアおよびterm listの作成者のひとりとして、コメントいたします。
 
本Term listなのですが、Hyperledger Fabricドキュメント日本語翻訳WGにて、
主にGlossaryページを翻訳した際に、コミュニティベースで議論しながら用語を整理したものがベースとなっております。
そして、コミュニティ内で利用している用語ですが、明確な理由があるものとないもの(最初の翻訳者がどういう用語を使ったにも寄る)があります。
 
そのため、明確な理由がないものに関して、本Term listの用語を採択するかどうかは、LFのほうでご判断頂くのがよろしいかと思います。
以下、リストアップ頂いた用語に関して、明確な理由があるものを列挙しますので、ご参考頂ければ幸いです。
 
- identity: 一般的なIDとは別の意味で使っているので、アイデンティティと訳すのがよいと思います。
- endorsment: Fabric v2.x以降で登場するapproveコマンドやapprovalとの混同を避けるために、「承認」とは訳さずにカタカナ表記にしています。ですので、これは区別できるようにしたほうが親切かもしれません。(endorsementとapprovalがそれぞれ登場する文章ではわかりづらくなる可能性があるため。)
- return: Term listの備考欄にもあります通り、ここでは投資の文脈での翻訳を表しておりますので、他の文脈(例えば関数)では「返す」で良いかと思います。
- committer: 未登場ですが、おそらくコミッタと訳すかと思います。
- orderer: カタカナ表記で「オーダラー」にするとあまりにもわかりづらかったため、コミュニティ内で自然と英語表記のままとなりました。
- それ以外については、明確な理由は特にないかと思います。表記は異なるのですが、軽微な違い・英語のままとするか否かなので、ドキュメント内で統一されているのであればどちらを使ってもよい気がしました。

**Comment by MieSato** [comment]
LFD271-JPで最終レビューと編集作業を行いましたので、簡単にコメントさせていただきます。

訳語は文脈によっても異なり、完全に統一すると日本語が不自然になることもあります。

技術用語で英語表記かカタカナ表記かを迷う場合は、初出部分で英語と日本語を併用するなどして、文書全体で統一されていればよいかと思います。LFD271-JPでもそのようにしているものが多いです。読者が混乱しないことが大事と考えます。

なお現行のLFの文書のスタイルは、基本的にこちらに従っています。
https://drive.google.com/file/d/1V5Rwx52C1Tm5dtTTHeu9zhmQDIwutdtO/view

**Comment by NaikiU** [comment]
ご回答ありがとうございました。参考にさせていただきます。
